### ISSUE TITLE
Get bootstrap-icons to work

### ISSUE THREAD

**Issue by jeffrey-zang** [lifeng-yin/simpleread#1]
![image](https://user-images.githubusercontent.com/66485719/179841840-be04a9b2-9536-47b3-8f01-44fe79f925db.png)
Nothing shows up even though bootstrap-icons is installed
![image](https://user-images.githubusercontent.com/66485719/179841903-74d40717-3893-4bc1-8291-07b8ea02a41f.png)
Very weird

**Comment by lifeng-yin** [comment]
I believe that just downloading it from npm does not work. It's not being imported in the html or anything. Using a CDN might work, put this into the <head> element: 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

**Comment by jeffrey-zang** [comment]
I'm assigning this task to you because I'm too lazy to figure this out
Also it appears in package-lock.json and it works on all my other projects
