### ISSUE TITLE
Fix nested li

### ISSUE THREAD

**Issue by Yourself1011** [lifeng-yin/simpleread#11]
```
<li> cannot appear as a descendant of <li>.
    at li
    at CustomLink 
    at li
    at ul
    at nav
    at Navbar
    at App
    at Router
    at BrowserRouter
```
The CustomLink component is returning a <li>, which is being put in another <li>, which is not allowed. I don't know the intended result so I don't know what to do.

**Comment by jeffrey-zang** [comment]
not a bug, doesn't really affect anything it just makes a warning in the console

**Comment by Yourself1011** [comment]
Which we want to avoid, right?

**Comment by jeffrey-zang** [comment]
yeah but i'm just saying it's not a game breaking thing

**Comment by Yourself1011** [comment]
It's still a bug
