### ISSUE TITLE
Get github pages to work

### ISSUE THREAD

**Issue by jeffrey-zang** [lifeng-yin/simpleread#6]

**Comment by jeffrey-zang** [comment]
The website works, but 
![image](https://user-images.githubusercontent.com/66485719/180883030-d7031ec3-79b6-4bc1-a3dc-f01929767cab.png)
so like you probably messed something up in the settings or something

**Comment by jeffrey-zang** [comment]
https://stackoverflow.com/questions/68497926/how-can-i-fix-failing-to-load-resource-status-404-github-pages

**Comment by Yourself1011** [comment]
It's showing ```html
      <h1>404</h1>
      <p><strong>There isn't a GitHub Pages site here.</strong></p>

      <p>
        If you're trying to publish one,
        <a href="https://help.github.com/pages/">read the full documentation</a>
        to learn how to set up <strong>GitHub Pages</strong>
        for your repository, organization, or user account.
      </p>
```
in sources

This probably has something to do with it

**Comment by Yourself1011** [comment]
[This](https://stackoverflow.com/a/46461290/11558361) might solve it @lifeng-yin

**Comment by Yourself1011** [comment]
It's probably because https://lifeng-yin.github.io doesn't exist

**Comment by jeffrey-zang** [comment]
probably lol

**Comment by Yourself1011** [comment]
resolved in #22
